- name: Deploy Dockerized Node.js app
  hosts: web
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Stop old container if running
      shell: |
        docker ps -q --filter "name=devops_app" | xargs -r docker stop
      ignore_errors: true

    - name: Remove old container if exists
      shell: |
        docker ps -a -q --filter "name=devops_app" | xargs -r docker rm
      ignore_errors: true

    - name: Pull Docker image with tag 7946053
      shell: docker pull janhavi001/devops-insights:7946053

    - name: Run new container
      shell: |
        docker run -d -p 80:3000 --name devops_app janhavi001/devops-insights:7946053
